name: EPG
on:
  push:
  schedule:
    - cron: 39 15,16 * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update EPG Files
      run: |
        rm -f e.xml && wget https://gitee.com/Black_crow/xmlgz/raw/master/e.xml -O e.xml
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add e.xml
        git commit -m "EPG Automatic Update."
    - name: Push changes
      run: git push -f origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
