name: EPG
on:
  push:
  schedule:
    - cron: 39 16,7 * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update EPG Files
      run: |
        rm -f e.xml && wget https://epg.112114.xyz/pp.xml -O e.xml
        rm -f e.xml.gz && wget https://epg.112114.xyz/pp.xml.gz -O e.xml.gz
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add all
        git commit -m "EPG Automatic Update."
    - name: Push changes
      run: git push -f origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
